baseURL = "https://blog.trentmason.id.au/"
languageCode = "en-au"
title = "Blog"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
  modality = "modalities"
  tag = "tags"

[params]
  author = "Trent Mason"
  description = "Notes, projects, and writing."

[permalinks]
  posts = "/posts/:slug/"

[markup]
  [markup.highlight]
    lineNos = false
    noClasses = true
